### ISSUE TITLE
How to install on an existing project

### ISSUE THREAD

**Issue by kinitkit** [cssninjaStudio/bulkit#10]
We already have an existing large project and planned to use bulkit. Our project is running in ReactJS. How do we install bulkit?

**Comment by cssninjaStudio** [comment]
Since you are using Reactjs, you will need to ditch all the jquery stuff and rewrite desired functions with vanilla. If you have a Sass loader installed with webpack or some other kind of bundler, just insert the Bulkit Sass files to be able to load them in your project. You should provide a single endpoint for all compiled css. You should also only include the parts that you will need for your project.

**Comment by kinitkit** [comment]
I think there will be no problem with jquery, since we are using a little bit of jquery also. From the file that we got from you, which folder is best for us to use? There are a lot of zipped files inside bulkit-2.1.0 and precompiled.

**Comment by cssninjaStudio** [comment]
Depends on what you want to do and what is your project. I guess it's an app project so you should use the dashboard kit.  Maybe unzip one gulp package to see what happens in there. Look at the package.json for dependencies and look inside gulpfile.js to see how assets are loaded, compiled or concatenated.

**Comment by kinitkit** [comment]
As what you've suggested, I think this will work if we copy what are needed from the package.json and copy how things are loaded, compiled or concatenated. I'll try this. Thanks

**Comment by cssninjaStudio** [comment]
No problem. Come back to me if any other questions.

**Comment by kinitkit** [comment]
I somehow got the scss working and there are a couple of conflicts with bootstrap, but no problem for now.

**Comment by cssninjaStudio** [comment]
Great to hear.
